readme and action added
OrgFlow-Actions/env-flowout pull request #4
Opened 2022-01-06 12:39 UTC by vickyvishal

2022-01-06 13:59 UTC, paynecrl97 commented
I've left quite a few comments on this unfortunately, but there may still be stuff I've missed which will be easier to catch once these first batch of issues are addressed.

RE testing- I'll add some tests to our testing sandboxes so that you can run them and test that code flow. Once that's working, the best thing to do IMO would be to update the workflow in the OFAPR repo to:

2022-01-06 14:01 UTC, paynecrl97 requested changes

2022-01-07 06:38 UTC, vickyvishal commented on action.yaml
> +        json=$(orgflow env:flowout --output=json -e="${{ inputs.environment-name }}" $(if [ "${{ inputs.test-level }}" -ne 'NoTestRun']; then --test="${{inputs.testClassNames}}"; fi) --jUnitTo="${{in
It threw error with double [[
https://github.com/OrgFlow-Actions/OFPR/runs/4725497345?check_suite_focus=true

2022-01-07 08:05 UTC, vickyvishal commented on README.md
> +    "commitResult":{
`outputs:
  result:
    description: "An array of JSON objects representing the results of the deployment to the source enviromnent."
    value: ${{ steps.env-flowout.outputs.result }}`
  I am not getting any output even after adding this to the `action.yaml` file. Am I missing something?

2022-01-07 10:40 UTC, paynecrl97 commented on action.yaml
> +        json=$(orgflow env:flowout --output=json -e="${{ inputs.environment-name }}" $(if [ "${{ inputs.test-level }}" -ne 'NoTestRun']; then --test="${{inputs.testClassNames}}"; fi) --jUnitTo="${{in
I think that's because `false` and `true` are not surrounded by double quotes though (the message is basically saying there's no command called `false`)

2022-01-07 10:41 UTC, paynecrl97 commented on README.md
> +    "commitResult":{
Can you link to a run where you were expecting the output to be printed please?

2022-01-07 10:42 UTC, paynecrl97 commented on action.yaml
> +        json=$(orgflow env:flowout --output=json -e="${{ inputs.environment-name }}" $(if [ "${{ inputs.test-level }}" -ne 'NoTestRun']; then --test="${{inputs.testClassNames}}"; fi) --jUnitTo="${{in
(The same might be true also for `NoTestRun` being surrounded by single quotes as opposed to double quotes)

2022-01-07 11:38 UTC, vickyvishal commented on action.yaml
> +        json=$(orgflow env:flowout --output=json -e="${{ inputs.environment-name }}" $(if [ "${{ inputs.test-level }}" -ne 'NoTestRun']; then --test="${{inputs.testClassNames}}"; fi) --jUnitTo="${{in
![image](https://user-images.githubusercontent.com/22187019/148538825-e6027ece-0ac2-492f-a329-25c8cb7aee43.png)

2022-01-12 11:55 UTC, vickyvishal commented
Done with the changes

2022-01-13 15:12 UTC, paynecrl97 requested changes

2022-01-13 15:12 UTC, paynecrl97 commented on README.md
> +| `test-level` | | | Indicates the tests that should be executed as part of the deployment to Salesforce. |
This input has a default

2022-01-13 15:12 UTC, paynecrl97 commented on README.md
> +#   checks: write
Either this works without this bit, in which case this should be removed.

Or it doesn't work without it, in which case these lines should be re-instated.

2022-01-13 15:12 UTC, paynecrl97 commented on README.md
> +        shell: bash
Why this step?

2022-01-13 15:12 UTC, paynecrl97 commented on action.yaml
> +    description: "An array of JSON objects representing the results of the deployment to the source enviromnent."
The output is not an array

2022-01-13 15:12 UTC, paynecrl97 commented on action.yaml
> +        json=$(orgflow env:flowout --output=json -e="${{ inputs.environment-name }}" --testLevel="${{inputs.test-level}}" $(if [ "${{ inputs.test-level }}" -eq "RunSpecifiedTests"]; then --tests="${{
The condition to use `jUnitTo` is not correct

2022-01-13 16:41 UTC, vickyvishal commented on README.md
> +        shell: bash
Just the boilerplate from `env:flowin` workflow. Think it's required since the flowout action has shell commands to run

2022-01-13 17:31 UTC, paynecrl97 commented on README.md
> +        shell: bash
I mean the step as a whole (line 128 to 129)- it does nothing but print the output, which I don't think we need in the example

2022-01-14 14:16 UTC, paynecrl97 commented
Just before I merge and publish this, could you link to a successful run of this action please?

2022-01-14 14:18 UTC, paynecrl97 commented on README.md
> +          files: ${{ env.RUNNER_TEMP }}MyTestResult.xml
Does this definitely work without the `checks: write` permission?

2022-01-14 16:17 UTC, vickyvishal commented on README.md
> +          files: ${{ env.RUNNER_TEMP }}MyTestResult.xml
`checks:write` https://github.com/OrgFlow-Actions/OFPR/actions/runs/1698347426
`content:read`  https://github.com/OrgFlow-Actions/OFPR/runs/4819227785?check_suite_focus=true 

Both the workflow fails
It passes without any permission

2022-01-18 16:58 UTC, merged